 # (key id) In the dropdown at top right by 'Horizon Preview' select 'Manage Access Keys' use the key id here.
access_key: ***************

# (secret key),  Select 'Show Secret Keys' from page above and copy in the secret key.
secret_key: *************** 

# eg "standard.xsmall|small|medium|large|xlarge"  See the 'Launch Instance' panel (here)[https://horizon.hpcloud.com/project/instances/] for details.
flavor: standard.small 

# (project id), Use the id listed on [this page](https://horizon.hpcloud.com/control_services/projects/).
tenant_id: ************* 

# eg "vagrant-test", machine name for the new server instance. Seems underscores are changed to dashes. 
server_name: test-server 

# Predefined image names available (here)[https://console.hpcloud.com/compute/region-a_geo-1/servers/new].
image: Ubuntu Precise 12.04 LTS Server 64-bit 20121026 (b) 

# eg "hp-vagrant-keypair", Create from the key pairs tab of [Access & Security](https://horizon.hpcloud.com/project/access_and_security/) page.
keypair_name: my-keyname 

# File path to key, generated by above step
ssh_private_key_path: ~/.ssh/my-key-file.pem

# HP provided image's login username
ssh_username: ubuntu 

# "us-west" or "us-east", More options are coming in the future.
availability_zone: us-east 

